Repository carsdotcom/skelebot, pull requests merged in 2019-10, with the labels that each got.

#82 Adding Registry Component
  CHANGELOG.md
  VERSION
  base-images/r-aws/Dockerfile
  docs/artifacts.md
  docs/index.md
  docs/publishing.md
  docs/versioning.md
  skelebot.yaml
  skelebot/components/componentFactory.py
  skelebot/components/registry.py
  skelebot/systems/execution/docker.py
  test/files/skelebot.yaml
  test/test_components_registry.py
  test/test_systems_execution_docker.py
  test/test_systems_generators_yaml.py
  test/test_systems_parsing_skeleParser.py
Labels: Hacktoberfest, feature

#83 Fixes Skelebot Env Param Bug
  CHANGELOG.md
  README.md
  VERSION
  skelebot-exp.yaml
  skelebot/skelebot.py
  test/test_skelebot_main.py
  test/test_systems_parsing_skeleParser.py
Labels: Hacktoberfest, bug

#84 Set Explicit Versions
  CHANGELOG.md
  VERSION
  setup.py
  skelebot.yaml
  test/test_systems_parsing_skeleParser.py
Labels: Hacktoberfest, task

#86 Styles README Logo
  CHANGELOG.md
  README.md
  VERSION
  test/test_systems_parsing_skeleParser.py
Labels: Hacktoberfest, task

#88 Update PyPI workflow to trigger on prereleases only
  .github/workflows/pypi-upload.yaml
  CHANGELOG.md
  VERSION
  test/test_systems_parsing_skeleParser.py
Labels: Hacktoberfest, task

#98 Env Parsing Bug
  CHANGELOG.md
  VERSION
  skelebot/skelebot.py
  test/test_skelebot_main.py
  test/test_systems_parsing_skeleParser.py
Labels: Hacktoberfest, bug

#100 test for install python dependencies from git and files
  CHANGELOG.md
  VERSION
  docs/dependencies.md
  skelebot/systems/generators/dockerfile.py
  test/test_systems_generators_dockerfile.py
  test/test_systems_parsing_skeleParser.py
Labels: Hacktoberfest, feature

#101 Readme Contributors
  CHANGELOG.md
  README.md
  VERSION
  skelebot.yaml
  skelebot/components/componentFactory.py
  test/test_systems_parsing_skeleParser.py
Labels: Hacktoberfest, task
