Repository carsdotcom/skelebot, pull requests merged in 2020-01, with the labels that each got.

#127 Execution Options for Primary Jobs
  CHANGELOG.md
  VERSION
  docs/jobs.md
  skelebot.yaml
  skelebot/objects/config.py
  skelebot/systems/execution/docker.py
  skelebot/systems/generators/dockerfile.py
  test/files/skelebot.yaml
  test/test_objects_config_validate.py
  test/test_systems_execution_docker.py
  test/test_systems_generators_dockerfile.py
Labels: feature

#130 excutor fail on non-zero status
  CHANGELOG.md
  VERSION
  skelebot/systems/execution/executor.py
  test/test_systems_execution_executor.py
Labels: bug

#131 Ecr registry
  CHANGELOG.md
  README.md
  VERSION
  docs/publishing.md
  skelebot/components/registry.py
  skelebot/systems/execution/docker.py
  test/files/skelebot-test.yaml
  test/test_components_registry.py
  test/test_systems_execution_docker.py
Labels: feature

#139 Adds missing scenarios in unit tests
  CHANGELOG.md
  VERSION
  test/test_systems_generators_dockerfile.py
Labels: task
